package:
  name: {{ CONDA_BUILD_NAME }}
  version: {{ CONDA_BUILD_VERSION }}

build:
  noarch: python
  skip: True # [win]
  script_env:
    - CONDA_BUILD_NAME
    - CONDA_BUILD_VERSION

test:
  imports:
    - airflow
    - airflow.api
    - airflow.api.auth
    - airflow.api.auth.backend
    - airflow.api.client
    - airflow.api.common
    - airflow.api.common.experimental
    - airflow.bin
    - airflow.config_templates
    - airflow.contrib
    - airflow.contrib.auth
    - airflow.contrib.auth.backends
    - airflow.contrib.executors
    - airflow.contrib.hooks
    - airflow.contrib.kubernetes
    - airflow.contrib.kubernetes.kubernetes_request_factory
    - airflow.contrib.operators
    - airflow.contrib.sensors
    - airflow.contrib.task_runner
    - airflow.contrib.utils
    - airflow.dag
    - airflow.example_dags
    - airflow.example_dags.subdags
    - airflow.executors
    - airflow.hooks
    - airflow.lineage
    - airflow.lineage.backend
    - airflow.macros
    - airflow.migrations
    - airflow.migrations.versions
    - airflow.operators
    - airflow.security
    - airflow.sensors
    - airflow.task
    - airflow.task.task_runner
    - airflow.ti_deps
    - airflow.ti_deps.deps
    - airflow.utils
    - airflow.utils.log
    - airflow.www
    - airflow.www.api
    - airflow.www.api.experimental
    - airflow.www_rbac
    - airflow.www_rbac.api
    - airflow.www_rbac.api.experimental

requirements:
  host:
    - python >=3.6,<3.7
    - pip
    - docutils >=0.14,<1.0
  run:
    - python >=3.6,<3.7
    - alembic >=0.8.3,<0.9
    - bleach >=2.1.3,<2.2
    - configparser >=3.5.0,<3.6.0
    - croniter >=0.3.17,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.12.4,<0.13
    - flask-appbuilder >=1.11.1,<2.0.0
    - flask-admin ==1.4.1
    - flask-caching >=1.3.3,<1.4.0
    - flask-login >=0.2.11,<0.5
    - flask-swagger ==0.2.13
    - flask-wtf >=0.14.2,<0.15
    - funcsigs ==1.0.0  # [py<33]
    - future >=0.16.0,<0.17
    - gitpython >=2.0.2
    - gunicorn >=19.4.0,<20.0
    - iso8601 >=0.1.12
    - jinja2 >=2.7.3,<2.9.0
    - lxml >=4.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.17.1,<1.0.0
    - pendulum ==1.4.4
    - psutil >=4.2.0,<5.0.0
    - pygments >=2.0.1,<3.0
    - python-daemon >=2.1.1,<2.2
    - python-dateutil >=2.3,<3
    - python-nvd3 ==0.15.0
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=1.1.15,<1.2.0
    - tabulate >=0.7.5,<=0.8.2
    - tenacity ==4.8.0
    - thrift >=0.9.2
    - tzlocal >=1.4
    - unicodecsv >=0.14.1
    - werkzeug >=0.14.1,<0.15.0
    - zope.deprecation >=4.0,<5.0
    - mysqlclient >=1.3.6


source:
  git_rev: HEAD
  git_url: ../../
