package:
  name: {{ CONDA_BUILD_NAME }}
  version: {{ CONDA_BUILD_VERSION }}

build:
  noarch: python
  skip: True # [win]
  script_env:
    - CONDA_BUILD_NAME
    - CONDA_BUILD_VERSION

test:
  imports:
    - airflow
    - airflow.api
    - airflow.api.auth
    - airflow.api.auth.backend
    - airflow.api.client
    - airflow.api.common
    - airflow.api.common.experimental
    - airflow.bin
    - airflow.config_templates
    - airflow.contrib
    - airflow.contrib.auth
    - airflow.contrib.auth.backends
    - airflow.contrib.executors
    - airflow.contrib.hooks
    - airflow.contrib.kubernetes
    - airflow.contrib.kubernetes.kubernetes_request_factory
    - airflow.contrib.operators
    - airflow.contrib.sensors
    - airflow.contrib.task_runner
    - airflow.contrib.utils
    - airflow.dag
    - airflow.example_dags
    - airflow.example_dags.subdags
    - airflow.executors
    - airflow.hooks
    - airflow.lineage
    - airflow.lineage.backend
    - airflow.macros
    - airflow.migrations
    - airflow.migrations.versions
    - airflow.operators
    - airflow.security
    - airflow.sensors
    - airflow.task
    - airflow.task.task_runner
    - airflow.ti_deps
    - airflow.ti_deps.deps
    - airflow.utils
    - airflow.utils.log
    - airflow.www
    - airflow.www.api
    - airflow.www.api.experimental
    - airflow.www_rbac
    - airflow.www_rbac.api
    - airflow.www_rbac.api.experimental

requirements:
  host:
    - python >=3.6,<=3.7
    - pip
    - docutils >=0.14,<1.0
    - gitpython >=2.0.2
  run:
    - python >=3.6,<=3.7
    - alembic>=1.0, <2.0
    - argcomplete~=1.10
    - attrs~=19.3
    - cached_property~=1.5
    - cattrs~=0.9
    - colorlog==4.0.2
    - configparser>=3.5.0, <3.6.0
    - croniter>=0.3.17, <0.4
    - dill>=0.2.2, <0.4
    - enum34~=1.1.6  # [py<34]
    - flask>=1.1.0, <2.0
    - flask-admin~=1.5.4
    - flask-appbuilder>=1.12.2, <2.0.0  # [py<36]
    - flask-appbuilder~=2.2  # [py>=36]
    - flask-caching>=1.3.3, <1.4.0
    - flask-login>=0.3, <0.5
    - flask-swagger==0.2.13
    - flask-wtf>=0.14.2, <0.15
    - funcsigs>=1.0.0, <2.0.0
    - future>=0.16.0, <0.17
    - graphviz>=0.12
    - gunicorn>=19.5.0, <20.0
    - iso8601>=0.1.12
    - jinja2>=2.10.1, <2.11.0
    - json-merge-patch==0.2
    - jsonschema~=3.0
    - lazy_object_proxy~=1.3
    - markdown>=2.5.2, <3.0
    - marshmallow-sqlalchemy>=0.16.1, <0.19.0  # [py<36]
    - pandas>=0.17.1, <1.0.0
    - pendulum==1.4.4
    - psutil>=4.2.0, <6.0.0
    - pygments>=2.0.1, <3.0
    - python-daemon>=2.1.1, <2.2
    - python-dateutil>=2.3, <3
    - requests>=2.20.0, <3
    - setproctitle>=1.1.8, <2
    - sqlalchemy~=1.3
    - sqlalchemy_jsonfield==0.8.0  # [py<35]
    - sqlalchemy_jsonfield~=0.9  # [py>=35]
    - tabulate>=0.7.5, <0.9
    - tenacity==4.12.0
    - termcolor==1.1.0
    - text-unidecode==1.2
    - thrift>=0.9.2
    - typing  # [py<35]
    - typing-extensions>=3.7.4  # [py<38]
    - tzlocal>=1.4,<2.0.0
    - unicodecsv>=0.14.1
    - werkzeug<1.0.0
    - zope.deprecation>=4.0, <5.0


source:
  git_rev: HEAD
  git_url: ../../
